question_data = [
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
        "question": "Which river flows through the Scottish city of Glasgow?", "correct_answer": "Clyde", "incorrect_answers": ["Tay", "Dee", "Tweed"]},
    {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "medium", "question": "In the webcomic Homestuck, the first character introduced is Dave Strider.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "General Knowledge", "type": "multiple", "difficulty": "easy", "question": "Which American-owned brewery led the country in sales by volume in 2015?", "correct_answer": "D. G. Yuengling and Son, Inc", "incorrect_answers": ["Anheuser Busch", "Boston Beer Company", "Miller Coors"]}, {"category": "Science: Mathematics", "type": "multiple", "difficulty": "easy", "question": "How many sides does a heptagon have?", "correct_answer": "7", "incorrect_answers": ["8", "6", "5"]}, {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium", "question": "What year did &quot;Bishoujo Senshi Sailor Moon&quot; air in Japan?", "correct_answer": "1992", "incorrect_answers": ["1989", "1990", "1994"]}, {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard", "question": "Which actress portrayed Dr. Grace Augustine in the James Cameron movie &quot;Avatar&quot;?", "correct_answer": "Sigourney Weaver", "incorrect_answers": [
        "Jessica Chastain", "Melissa Beckett", "Alyssa Monroe "]}, {"category": "Entertainment: Television", "type": "multiple", "difficulty": "hard", "question": "What was the name of the inflatable duck sacrified to the crowd at the end of Episode 34 of the 18th season of Big Brother?", "correct_answer": "Pablo", "incorrect_answers": ["Esteban", "Carlos", "Duckster"]}, {"category": "Celebrities", "type": "multiple", "difficulty": "easy", "question": "By which name is Ramon Estevez better known as?", "correct_answer": "Martin Sheen", "incorrect_answers": ["Charlie Sheen", "Ramon Sheen", "Emilio Estevez"]}, {"category": "General Knowledge", "type": "multiple", "difficulty": "easy", "question": "Which of the following is not the host of a program on NPR?", "correct_answer": "Ben Shapiro", "incorrect_answers": ["Terry Gross", "Ira Glass", "Peter Sagal"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy", "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.", "correct_answer": "True", "incorrect_answers": ["False"]}
# {"question": "A slug's blood is green.", "answer": "True"},
# {"question": "The loudest animal is the African Elephant.", "answer": "False"},
# {"question": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
# {"question": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
# {"question": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
# {"question": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
# {"question": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
# {"question": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
# {"question": "Google was originally called 'Backrub'.", "answer": "True"},
# {"question": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
# {"question": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
# {"question": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]
